#!/bin/bash
# Sportio E2E Test Setup Script
# Usage: ./tests/e2e/setup.sh <DATABASE_URL> [GOOGLE_CLIENT_ID] [GOOGLE_CLIENT_SECRET]

set -e

echo "╔══════════════════════════════════════════╗"
echo "║  SPORTIO E2E - Setup do Ambiente         ║"
echo "╚══════════════════════════════════════════╝"

DATABASE_URL="${1:-$DATABASE_URL}"
GOOGLE_CLIENT_ID="${2:-$GOOGLE_CLIENT_ID}"
GOOGLE_CLIENT_SECRET="${3:-$GOOGLE_CLIENT_SECRET}"

if [ -z "$DATABASE_URL" ]; then
  echo "❌ DATABASE_URL é obrigatório!"
  echo "   Uso: ./tests/e2e/setup.sh 'postgres://user:pass@host/db?sslmode=require'"
  exit 1
fi

echo "📝 Criando .env.local..."
cat > .env.local << EOF
# Auto-generated by E2E setup - $(date)
DATABASE_URL=${DATABASE_URL}
AUTH_SECRET=$(openssl rand -base64 32)
AUTH_URL=http://localhost:3000
NEXTAUTH_URL=http://localhost:3000
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
NEXT_PUBLIC_SITE_URL=http://localhost:3000
NODE_ENV=development
EOF

echo "✅ .env.local criado"

echo "📦 Instalando dependências..."
pnpm install --frozen-lockfile 2>/dev/null || pnpm install

echo "🗄️ Fazendo push do schema para o banco..."
pnpm db:push

echo "🌱 Seedando banco de dados..."
pnpm db:seed || echo "⚠️ Seed pode ter falhado (dados já existem?)"

echo ""
echo "✅ SETUP COMPLETO!"
echo ""
echo "Para rodar os testes:"
echo "  1. Inicie o servidor: pnpm dev &"
echo "  2. Aguarde o servidor iniciar (~10s)"
echo "  3. Execute: npx tsx tests/e2e/run-all.ts"
echo ""
